import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ModalWrapper from '@/components/modalWraper'
import { useModal } from '@/store/newStore'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {isOpen,toggleOpen}=useModal()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main  className=' relative flex min-h-screen w-full'>

          <button onClick={toggleOpen} className='h-fit m-auto text-3xl rounded-xl border-2 px-10 py-2 font-semibold hover:scale-105  transition-all duration-150 ease-linear'>Book an appointment</button>

            {isOpen&&<ModalWrapper/>}
      </main>
    </>
  )
}
